declare namespace lib {
  interface Observable<T> {
    subscribe(handler: (newVal: T) => any): void;
  }
  class SimpleObservable<T> implements Observable<T> {
    constructor(initialVal: T);
    set(newVal: T): void;
    subscribe(handler: (newVal: T) => any): void;
    value: T;
  }
  interface Thenable<T> {
    then(handler: (val: T) => any): void;
  }
  type Child = HTMLElement|string|Observable<HTMLElement|string>|Thenable<HTMLElement|string>
  function nodeCreator(nodeName: keyof HTMLElementTagNameMap): (attributes?: object|Child, ...children: Array<Child>) => HTMLElement;
  function a(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function abbr(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function address(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function applet(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function area(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function article(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function aside(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function audio(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function b(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function base(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function basefont(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function bdi(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function bdo(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function blockquote(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function body(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function br(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function button(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function canvas(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function caption(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function cite(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function code(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function col(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function colgroup(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function data(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function datalist(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function dd(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function del(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function details(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function dfn(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function dialog(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function dir(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function div(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function dl(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function dt(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function em(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function embed(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function fieldset(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function figcaption(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function figure(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function font(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function footer(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function form(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function frame(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function frameset(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function h1(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function h2(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function h3(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function h4(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function h5(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function h6(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function head(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function header(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function hgroup(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function hr(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function html(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function i(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function img(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function input(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function ins(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function kbd(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function label(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function legend(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function li(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function link(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function main(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function map(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function mark(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function marquee(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function menu(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function meta(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function meter(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function nav(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function noscript(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function object(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function ol(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function optgroup(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function option(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function output(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function p(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function param(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function picture(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function pre(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function progress(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function q(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function rp(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function rt(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function ruby(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function s(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function samp(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function script(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function section(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function select(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function slot(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function small(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function source(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function span(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function strong(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function style(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function sub(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function summary(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function sup(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function table(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function tbody(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function td(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function template(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function textarea(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function tfoot(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function th(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function thead(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function time(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function title(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function tr(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function track(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function u(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function ul(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function varNode(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function video(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
  function wbr(attributes?: object|Child, ...children: Array<Child>): HTMLElement;
}

export = lib